#!/bin/bash

# Source the helpers
if [ -f "/tmp/test-lib.sh" ]; then
    source /tmp/test-lib.sh
else
    echo "ERROR: Can't find test-lib.sh"
    exit 1
fi

#
# TEST
#
toReturn=PASSED

while read -r line; do
    file=`echo -e "$line" | awk '{ print $2 }'`
    md5=`echo "$line" | awk '{ print $1 }'`
    if [ ! -f $file ]; then
        log DEBUG "$file doesn't exist on the filesystem anymore ."
        toReturn=FAILED
    else
        realmd5=`md5sum $file | awk '{ print $1 }'`
        if [ "$md5" != "$realmd5" ]; then
            log DEBUG "$file has MD5=$realmd5 when it should be $md5 ."
            toReturn=FAILED
        fi
   fi
done < /resin-root.fingerprint

log $toReturn
