#!/bin/bash

# Help function
function help {
    cat << EOF
Run tests
$0 <OPTION>

Options:
  -h, --help
        Display this help and exit.

  -u <UUID>, --uuid <UUID>
        Update this UUID.

  -s <SSH_HOST>, --ssh-host <SSH_HOST>
        SSH host to be used in ssh connections. and other places. Please have them called

  -t <TESTNAME>, --testname <TESTNAME>
        Run this test.
EOF
}

# Log function helper
function log {
    # Address log levels
    case $1 in
        ERROR)
            loglevel=ERROR
            shift
            ;;
        WARN)
            loglevel=WARNING
            shift
            ;;
        *)
            loglevel=LOG
            ;;
    esac
    ENDTIME=$(date +%s)
    if [ "z$LOG" == "zyes" ]; then
        printf "[%09d%s%s\n" "$(($ENDTIME - $STARTTIME))" "][$loglevel]" "$1" | tee -a $LOGFILE
    else
        printf "[%09d%s%s\n" "$(($ENDTIME - $STARTTIME))" "][$loglevel]" "$1"
    fi
    if [ "$loglevel" == "ERROR" ]; then
        exit 1
    fi
}

#
# MAIN
#

# Get the absolute script location
pushd `dirname $0` > /dev/null 2>&1
SCRIPTPATH=`pwd`
popd > /dev/null 2>&1

# Log timer
STARTTIME=$(date +%s)

# Parse arguments
while [[ $# > 0 ]]; do
    arg="$1"

    case $arg in
        -h|--help)
            help
            exit 0
            ;;
        -u|--uuid)
            if [ -z "$2" ]; then
                log ERROR "\"$1\" argument needs a value."
            fi
            UUID="$2"
            shift
            ;;
        -s|--sshhost)
            if [ -z "$2" ]; then
                log ERROR "\"$1\" argument needs a value."
            fi
            SSH_HOST=$2
            shift
            ;;
        -t|--testname)
            if [ -z "$2" ]; then
                log ERROR "\"$1\" argument needs a value."
            fi
            TESTNAME=$2
            shift
            ;;
        *)
            log ERROR "Unrecognized option $1."
            ;;
    esac
    shift
done

# Check argument(s)
if [ -z "$UUID" ] || [ -z "$SSH_HOST" ]; then
    log ERROR "No UUID and/or SSH_HOST specified."
fi

if [ -z "$TESTNAME" ]; then
    log WARN "No testname specified. Will run all."
    TESTPATHS=$(find $SCRIPTPATH/tests -type f)
    slug=$(ssh $SSH_HOST -o Hostname=$UUID.vpn jq -r .deviceType /mnt/conf/config.json)
    if [ -z "$slug" ]; then
        log ERROR "Can't find machine slug"
    fi
    if [ -d $SCRIPTPATH/tests/$slug ]; then
        TESTPATHS="$TESTPATHS $(find $SCRIPTPATH/tests/$slug -type f)"
    else
        log WARN "No machine specific tests for $slug."
    fi
else
    TESTPATHS=$(find $SCRIPTPATH/tests/all -type f -name $TESTNAME)
fi

if [ -z "$TESTPATHS" ]; then
    log ERROR "No tests found."
else
    log "The following tests will be ran:"
    for tp in $TESTPATHS; do
        log "   $tp"
    done
fi

log "Transfering helpers on target..."
HELPERS=$(find $SCRIPTPATH/helpers -type f)
scp -o Hostname=$UUID.vpn $HELPERS $SSH_HOST:/tmp &> /dev/null
if [ $? -ne 0 ]; then
    log ERROR "Failed to transfer helpers on target"
fi

FAILED=0
TOTAL=0

echo
for tp in $TESTPATHS; do
    tn=$(basename $tp)
    log "[$tn] Transfering test on target..."
    scp -o Hostname=$UUID.vpn $tp $SSH_HOST:/tmp/$tn  &> /dev/null
    if [ $? -ne 0 ]; then
        log ERROR "Failed to transfer test on target"
    fi

    log "[$tn] Running on target..."
    ssh $SSH_HOST -o Hostname=$UUID.vpn /tmp/$tn
    if [ $? -ne 0 ]; then
        FAILED=$((FAILED+1))
    fi
    TOTAL=$((TOTAL+1))
    echo
done

log "Test results"
log "Failed tests: $FAILED"
log "Total tests : $TOTAL"

if [ $FAILED -gt 0 ]; then
    exit 1
fi
