#!/bin/bash

# Source the helpers
if [ -f "/tmp/test-lib.sh" ]; then
    source /tmp/test-lib.sh
else
    echo "ERROR: Can't find test-lib.sh"
    exit 1
fi

#
# TEST
#
while read line; do
    file=`echo "$line" | awk '{ print $2 }'`
    md5=`echo "$line" | awk '{ print $1 }'`
    realmd5=`md5sum $file | awk '{ print $1 }'`
    if [ "$md5" != "$realmd5" ]; then
        log DEBUG "$file has MD5=$realmd5 when it should be $md5 ."
        log ERROR "TEST FAILED"
    fi
done < /resin-root.fingerprint

log INFO "TEST PASSED"
